name: Cache Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-deps
          key: cache-7e28408

      - name: prime-cache-7e28408
        id: prime-cache-7e28408
        run: echo "Cache result: ${{ steps.cache-deps.outputs.cache-hit }}"
